name: Run Match Fetcher

on:
  schedule:
    - cron: "0 * * * *"  # her saat başı
  workflow_dispatch:      # manuel çalışma için opsiyonel

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install requests thefuzz playwright python-dateutil beautifulsoup4
        pip install playwright
        playwright install --with-deps

    - name: Run script
      run: |
        python fetch_match_program.py

    - name: Commit updated CSV
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add super_lig_match_program.csv

        # değişiklik varsa commit et
        git commit -m "Update CSV (automatic run)" || echo "No changes to commit"
        git push
